# Generated by Django 4.2.29 on 2026-04-01 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
        ('novels', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.PROTECT, to='masters.masterclass')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='worlds.setting')),
            ],
            options={
                'db_table': 'worlds_setting',
            },
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'worlds_world',
            },
        ),
        migrations.CreateModel(
            name='WorldTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.tag')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.world')),
            ],
            options={
                'db_table': 'worlds_worldtag',
                'unique_together': {('world', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='WorldStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.masterstatus')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='worlds.world')),
            ],
            options={
                'db_table': 'worlds_worldstatus',
            },
        ),
        migrations.CreateModel(
            name='WorldInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('world', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='worlds.world')),
            ],
            options={
                'db_table': 'worlds_worldinfo',
            },
        ),
        migrations.CreateModel(
            name='WorldCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.category')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.world')),
            ],
            options={
                'db_table': 'worlds_worldcategory',
                'unique_together': {('world', 'category')},
            },
        ),
        migrations.AddField(
            model_name='world',
            name='categories',
            field=models.ManyToManyField(related_name='worlds', through='worlds.WorldCategory', to='common.category'),
        ),
        migrations.AddField(
            model_name='world',
            name='novel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worlds', to='novels.novel'),
        ),
        migrations.AddField(
            model_name='world',
            name='tags',
            field=models.ManyToManyField(related_name='worlds', through='worlds.WorldTag', to='common.tag'),
        ),
        migrations.AddField(
            model_name='world',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worlds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SettingField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='worlds.setting')),
            ],
            options={
                'db_table': 'worlds_settingfield',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='setting',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='worlds.world'),
        ),
        migrations.CreateModel(
            name='SettingRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='worlds.setting')),
                ('to_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='worlds.setting')),
            ],
            options={
                'db_table': 'worlds_settingrelation',
                'unique_together': {('from_setting', 'to_setting', 'relation_label')},
            },
        ),
    ]
