# Generated by Django 5.2.17 on 2026-09-03 04:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1024)])),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='world_covers/')),
                ('owner_pen_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worlds', to='accounts.penname')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
