# Generated by Django 4.2.29 on 2026-04-01 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=50000)),
                ('sort_order', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'novels_episode',
                'ordering': ['sort_order', 'episode_number'],
            },
        ),
        migrations.CreateModel(
            name='EpisodeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'novels_episodestatus',
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.category')),
            ],
            options={
                'db_table': 'novels_novel',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='novels.novel')),
            ],
            options={
                'db_table': 'novels_section',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='novels.section')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.masterstatus')),
            ],
            options={
                'db_table': 'novels_sectionstatus',
            },
        ),
        migrations.CreateModel(
            name='NovelTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.tag')),
            ],
            options={
                'db_table': 'novels_noveltag',
            },
        ),
        migrations.CreateModel(
            name='NovelStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='novels.novel')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.masterstatus')),
            ],
            options={
                'db_table': 'novels_novelstatus',
            },
        ),
        migrations.CreateModel(
            name='NovelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('synopsis', models.TextField(blank=True, max_length=1000, null=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_r18', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('novel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='novels.novel')),
            ],
            options={
                'db_table': 'novels_novelinfo',
            },
        ),
        migrations.AddField(
            model_name='novel',
            name='tags',
            field=models.ManyToManyField(related_name='novels', through='novels.NovelTag', to='common.tag'),
        ),
    ]
