# Generated by Django 4.2.29 on 2026-04-01 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='episodestatus',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='novels.episode'),
        ),
        migrations.AddField(
            model_name='episodestatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.masterstatus'),
        ),
        migrations.AddField(
            model_name='episode',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='novels.novel'),
        ),
        migrations.AddField(
            model_name='episode',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='novels.section'),
        ),
        migrations.AlterUniqueTogether(
            name='noveltag',
            unique_together={('novel', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('novel', 'episode_number')},
        ),
    ]
