# Generated by Django 4.2.29 on 2026-04-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.BigIntegerField()),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'administration_operationhistory',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('target_id', models.BigIntegerField()),
                ('body', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', '未対応'), ('resolved', '解決'), ('dismissed', '却下')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'administration_report',
            },
        ),
        migrations.CreateModel(
            name='WorkStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.BigIntegerField(default=0)),
                ('episode_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('good_count', models.IntegerField(default=0)),
                ('bookmark_count', models.IntegerField(default=0)),
                ('rating_sum', models.BigIntegerField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'administration_workstat',
            },
        ),
    ]
