# Generated by Django 4.2.29 on 2026-04-01 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('novels', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstat',
            name='novel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='novels.novel'),
        ),
        migrations.AddField(
            model_name='report',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.masterreason'),
        ),
    ]
