# Generated by Django 4.2.29 on 2026-04-01 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0002_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationhistory',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.masteroperation'),
        ),
        migrations.AddField(
            model_name='operationhistory',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.mastertable'),
        ),
        migrations.AddField(
            model_name='operationhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='operationhistory',
            index=models.Index(fields=['table', 'target_id'], name='administrat_table_i_f6a299_idx'),
        ),
    ]
